
export const LOAD_INVOICES = 'LOAD_INVOICES';
export const LOAD_INVOICES_SUCCESS = 'LOAD_INVOICES_SUCCESS';
export const LOAD_INVOICES_ERROR = 'LOAD_INVOICES_ERROR';

export const ADD_INVOICE = 'ADD_INVOICE';
export const ADD_INVOICE_SUCCESS = 'ADD_INVOICE_SUCCESS';
export const ADD_INVOICE_ERROR = 'ADD_INVOICE_ERROR';

export const DELETE_INVOICE = 'DELETE_INVOICE';
export const FILTER_INVOICES = 'FILTER_INVOICES';

export const LOAD_INVOICE = 'LOAD_INVOICE';
export const LOAD_INVOICE_SUCCESS = 'LOAD_INVOICE_SUCCESS';

export const EDIT_INVOICE = 'EDIT_INVOICE';
export const EDIT_INVOICE_SUCCESS = 'EDIT_INVOICE_SUCCESS';
export const EDIT_INVOICE_ERROR = 'EDIT_INVOICE_ERROR';

export const CHANGE_INVOICE_FORM = 'CHANGE_INVOICE_FORM';
export const ADD_ITEM = 'ADD_ITEM';
export const CHANGE_ITEM_AMOUNT = 'CHANGE_ITEM_AMOUNT';
export const CHANGE_ITEM_DETAIL = 'CHANGE_ITEM_DETAIL';
export const DELETE_ITEM = 'DELETE_ITEM';

export const CHANGE_STATUS_INVOICE = 'CHANGE_STATUS_INVOICE';

export const PRINT = 'PRINT';
