export const LOAD_CLIENTS = 'LOAD_CLIENTS';
export const LOAD_CLIENTS_SUCCESS = 'LOAD_CLIENTS_SUCCESS';
export const LOAD_CLIENTS_ERROR = 'LOAD_CLIENTS_ERROR';
export const SELECT_CLIENT = 'SELECT_CLIENT';
